### ISSUE TITLE
Discuss how to write docs

### ISSUE THREAD

**Issue by negbie** [balerter/balerter#12]
The current way of documentation is done via github pages which is quite inconvenient for new contributors.

Maybe a better way would be to use something like https://readthedocs.org/ and add a link on the homepage? What do you think or do you have a suggestion for something else?

**Comment by negasus** [comment]
The documentation site was built in haste. Using a more suitable solution is a good idea. I will look at readthedocs.org

**Comment by negbie** [comment]
Another option would be https://antora.org/

**Comment by negasus** [comment]
Oh. I'm looking for options too right now ) I dont see site examples with antora. Maybe I'm not looking carefully (

**Comment by negbie** [comment]
Link to homepage: https://sip3.io/docs/tutorials/HowToInroduceUserDefinedAttribute.html
Link to docs repo: https://github.com/sip3io/sip3-documentation

**Comment by negbie** [comment]
Best way would be to reuse your markdown files here: https://github.com/balerter/site/tree/master/content

**Comment by negbie** [comment]
Or mby https://docusaurus.io/en/

**Comment by negbie** [comment]
docusaurus seems pretty simple and you could just copy over all your markdown files.

**Comment by negbie** [comment]
Let's close this here. I think the homepage is just fine.
