### ISSUE TITLE
Mattermost/Slack incoming webhooks

### ISSUE THREAD

**Issue by negbie** [balerter/balerter#19]
Do you think it makes sense to add Mattermost/Slack webhooks or do you mean something else in the project description with channel: webhook?

**Comment by negasus** [comment]
We already have 'Slack' channel. I think, we should use builtin integrations for mainstream things. And add webhook for other: custom user integration etc.
I think, Mattermost is good candidate for butilin integration.

I think, we should create Project tasks for builtint integrations?

**Comment by negbie** [comment]
At work we use Mattermost and since it's compatible with Slacks webhooks I often integrated external programs into Mattermost with Slack webhooks.

**Comment by negasus** [comment]
Maybe we can leave a name 'Slack' for the cleanliness of the config?

**Comment by negasus** [comment]
Use 'Slack' for slack and mattermost channel
