### ISSUE TITLE
Rename repeat field from alertOptions

### ISSUE THREAD

**Issue by negbie** [balerter/balerter#20]
Any name suggestions? I would propose "trigger"

**Comment by negasus** [comment]
Maybe 'repeatBy', because it option makes sense: repeat every X times? I think, 'trigger' is best choice for fire some event, not for repeating.

**Comment by negbie** [comment]
repeatBy is a composed word. Mby we can find a single one? Mby retry?

**Comment by negasus** [comment]
`repeat` is the best choice. I still don’t know what to choose)

**Comment by negbie** [comment]
Hehe yeah thought the same ;)

**Comment by negasus** [comment]
Let’s leave it like this until the users complain)

**Comment by negbie** [comment]
Ok
