### ISSUE TITLE
Create some examples

### ISSUE THREAD

**Issue by negbie** [balerter/balerter#27]
Hi @negasus 
what do you think about adding a example folder with some more examples? Currently I play with following:

Use yahoo finance API to fetch some predefined stocks and save the value into KV store. Next API call I check if the returned value is a predefined amount of % lower than the previous one and fire an alert.

**Comment by negbie** [comment]
For that I currently use the Discord Channel with a Bot account.

**Comment by negasus** [comment]
Maybe we can use chapter 'Examples'  from the site https://balerter.com/en/examples/ ?

We can add extra info, images etc.

**Comment by negbie** [comment]
Ah yes that's a good idea! Let me try to finish my example and send it to you.
