### ISSUE TITLE
Make `logLevel` and `debug` flag values known to lua scripts

### ISSUE THREAD

**Issue by yuyutime** [balerter/balerter#3]
It is a common case that many diagnostic output statements like `print()` or `log.debug()` statements are used  in script while lua script is under development and not needed in production version.
Also, some fragments of script are often only required during debug runs and have to be turned off somehow in production code.

Currently lua scripts are unaware of the values for `logLevel` and `debug` flags used when running **balerter**. If would be useful to make those values available in scripts at runtime.
Then one can write code like this:
```lua
if runtime.logLevel == 'INFO' then print('info') end
if runtime.debug then <some debug related code here> end

```

**Comment by negasus** [comment]
A module `runtime` uploaded to the master branch. Wait for the release soon.
