### ISSUE TITLE
Add support for external data push

### ISSUE THREAD

**Issue by zhum** [balerter/balerter#34]
Please, add an API for external http requests to push alerts from outside world.

**Comment by negasus** [comment]
To change alerts status from outside you can use [API](https://balerter.com/0.7.0/api/api.html).
Its solved your problem?

**Comment by zhum** [comment]
Thank you! It **almost** all I need. Could you add to API a method to force a script to start with some arguments? I mean a scenario similar to this:
- snmp-trap daemon cathes a trap
- it send it to baterter with type, source and some other info about this trap
- balerter calls a special script, which process this event as usual, but having access to passed information
- happiness and joy!
I think, this scenario is better to implement with "push" pattern over "put it in the database and check every N minutes", and it does not exclude traditional approach (but enhances it). We have many cases like this...

**Comment by negasus** [comment]
Looks like API  (for example)`POST ... / script` with the script body as the payload, right?

**Comment by zhum** [comment]
Script in the body is not a good for security reason, I think. I prefer `POST ... /push` with json payload and special lua function `on_push` (e.g.), which is called on each POST.

**Comment by negasus** [comment]
Merged in  #41
