### ISSUE TITLE
Help on email

### ISSUE THREAD

**Issue by negbie** [balerter/balerter#5]
Hi @negasus would it be ok for you if I would pick up the email channel to do?

**Comment by negasus** [comment]
Hi!
It will be come soon ;)

**Comment by negbie** [comment]
So you are have already wokred on it? Otherwise I would start working on it and contribute the code back.

**Comment by negbie** [comment]
I just want to make sure that I don't start when you are already working on it. That's the reason of my question.

**Comment by negasus** [comment]
Oh yes, you can help) I still haven't started. Planned next week

**Comment by negasus** [comment]
I'm working on integrations tests https://github.com/balerter/balerter/projects/1

**Comment by negbie** [comment]
Ok thanks. I will start working on email.

**Comment by negbie** [comment]
Added maildev to the docker-compose maybe it's better to use https://github.com/mailhog/MailHog
