### ISSUE TITLE
Implement support for Cadence

### ISSUE THREAD

**Issue by ryancox** [balerter/balerter#55]
The built in cron support via https://github.com/robfig/cron is somewhat limiting in that it can only run on a single system and has no UI/tooling. Adding support for [Cadence ](https://github.com/uber/cadence) might not be that difficult and would allow for scaling balerter significantly. 

[Example cron workflow](https://github.com/uber-common/cadence-samples/tree/master/cmd/samples/cron)

**Comment by negasus** [comment]
This is an interesting idea. I have to research this feature

**Comment by ryancox** [comment]
Amazing! I realized after logging this issue that what I was really interested in was support for Temporal. This is a fork of Cadence so should be very similar in terms of implementation. It's getting way more traction by companies than Cadence and uses proto/grpc and other tech that aligns better to my use case. I'm pretty confident this would be of more use to balerter users generally. I do have some experience playing with Temporal and would be happy to port over what you have and test it. 

I'm imagining two modes: worker and runner. Where runner loads jobs and worker that handles execution. Example: https://github.com/temporalio/samples-go/tree/main/cron

**Comment by ryancox** [comment]
ah found your branch here https://github.com/balerter/balerter/compare/feature/cadence

**Comment by negasus** [comment]
Yes, it actual branch. You need to define in config file:

```hcl
cadence {
  worker "w1" {
    host           = "127.0.0.1:7933"
    domain         = "balerter"
    taskListName   = "balerter"
    clientName     = "balerter1"
    cadenceService = "cadence-frontend"
    workflowAlias  = "b1"
  }
}
```

And send to worker the payload with scripts name array. For example: ["folder.demo.myscipt"]

**Comment by negasus** [comment]
You can define `-- @ignore` meta tag into script for prevent auto run

**Comment by ryancox** [comment]
This approach could be a fine place to start. But one comment about the way https://github.com/balerter/balerter/blob/da89802926022d58e6f835591d3decf979a198d8/internal/cadence/cadence.go is structured. This fits nicely with balerter's existing architecture where a Runner handles job registration and execution. But in a Cadence/Temporal system, this would seem to limit you to a single instance. Whereas if execution was handled in a distinct worker, those workers could scale up and down. Take a look at how most of the samples are structured with 'starters' and 'workers' https://github.com/temporalio/samples-go/tree/main/cron.

**Comment by negasus** [comment]
Thanks for the advice. I will definitely look. I will also try Temporal

**Comment by negasus** [comment]
The question is about scaling workers. As I understand it, the client does not automatically scale them. Instead, we have to run the required number of workers. In the configuration, we can specify the required number of worksets for one instance of a ballerter. Or did you mean something else about scaling?

**Comment by negasus** [comment]
I added initial Temporalio support to the cadence branch

config:

```hcl
temporalio {
  worker "w1" {
    host          = "localhost:7233"
    namespace     = "balerter"
    workflowAlias = "b1"
    taskQueueName = "balerter"
  }
}
```

**Comment by ryancox** [comment]
thanks! I'll find some time this weekend to play with it. with respect to scaling, i was more thinking about running multiple instances of balerter workers vs the problem of auto scaling. If you want to run 10, 100 or 1000 instances of balerter workers, it would be necessary to break out the 'starter' or job loader part of the worker into it's own discrete component. You would only need one instance of that, no matter how many instances you have of the worker itself.
