### ISSUE TITLE
Additional cron based runJob

### ISSUE THREAD

**Issue by negbie** [balerter/balerter#7]
The current watcher is Interval (time.Duration) based. A cron based watcher would allow some kind of reporting functionality. What do you think?

**Comment by negasus** [comment]
Can you explain your proposal? Maybe with an example?

**Comment by negbie** [comment]
Sure, currently in scripts "@interval" keyword is parsed into a time.Duration interval which will picked up by the runner in the runJob func.

Maybe it would be useful to have a @cron keyword and the runJob is scheduled by https://github.com/robfig/cron

**Comment by negasus** [comment]
Yes, that's a good idea. I thought about it. This will require some refactoring.

**Comment by negasus** [comment]
Fix will be soon published with massive refactoring
