### ISSUE TITLE
Add CSV en/decoding

### ISSUE THREAD

**Issue by negbie** [balerter/balerter#9]
Currently there is json en/decoding. Mby it would be good to have a fast CSV en/decoder. Could be useful for anomaly detection later on...

Mby https://github.com/FourierTransformer/ftcsv what do you think?

**Comment by negasus** [comment]
We are talking about logging?

**Comment by negasus** [comment]
Oh, we are talking about lua module? We can use lua modules as is. Add any files in /modules and include in scripts

**Comment by negbie** [comment]
I was talking about lua modules and since json is already there mby CSV would make sense too.

**Comment by negasus** [comment]
All data source modules returns data as Lua table. That table can be converted to string (json, csv, tsv etc) with lua modules. So, we can add predefined lua module. Did i understand correctly?

**Comment by negbie** [comment]
Yes. Of course the user can do this him self but it's more convenient if there a some default modules which are tested and work well with Lua tables.

**Comment by negasus** [comment]
I think, that a good idea. Add a default lua module for working with csv. Can you make it?

**Comment by negbie** [comment]
Jeah I can look into some libs and see whichs works well with lua tables. Could you please add it to projects todo?

**Comment by negasus** [comment]
I can add you to the balerter team) Do it?

**Comment by negbie** [comment]
It's up to you but sure why not. Currently I'm on vacation and since you cannot travel I have some time to contribute ;)
